### ISSUE TITLE
Issues on connection - Exception

### ISSUE THREAD

**Issue by VoidWhisperer** [Top-Cat/SteamKit-Java#6]
```
java.security.InvalidKeyException: Illegal key size or default parameters
    at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1011)
    at javax.crypto.Cipher.init(Cipher.java:1209)
    at javax.crypto.Cipher.init(Cipher.java:1153)
    at uk.co.thomasc.steamkit.util.crypto.CryptoHelper.SymmetricEncrypt(CryptoHelper.java:114)
    at uk.co.thomasc.steamkit.networking.steam3.NetFilterEncryption.processOutgoing(NetFilterEncryption.java:20)
    at uk.co.thomasc.steamkit.networking.steam3.TcpConnection.send(TcpConnection.java:115)
    at uk.co.thomasc.steamkit.steam3.CMClient.send(CMClient.java:234)
    at uk.co.thomasc.steamkit.steam3.handlers.steamuser.SteamUser.logOn(SteamUser.java:99)
    at info.voidwhisperer.steambot.BaseBot$1.call(BaseBot.java:72)
    at info.voidwhisperer.steambot.BaseBot$1.call(BaseBot.java:1)
    at uk.co.thomasc.steamkit.steam3.steamclient.callbackmgr.CallbackMsg.handle(CallbackMsg.java:40)
    at info.voidwhisperer.steambot.BaseBot.handleSteamCallbackMessage(BaseBot.java:64)
    at info.voidwhisperer.steambot.BaseBot.Update(BaseBot.java:59)
    at info.voidwhisperer.steambot.BaseBot.<init>(BaseBot.java:39)
    at info.voidwhisperer.steambot.Main.main(Main.java:9)
```

Is the exception I am getting. Am I doing something wrong or is it steamkit just not working anymore?

**Comment by Top-Cat** [comment]
> Due to import control restrictions by the governments of a few countries, the jurisdiction policy files shipped specify that “strong” but limited cryptography may be used. An “unlimited strength” version of these files indicating no restrictions on cryptographic strengths is available for those living in eligible countries (which is most countries). But only the “strong” version can be imported into those countries whose governments mandate restrictions. The JCE framework will enforce the restrictions specified in the installed jurisdiction policy files.

You'll need to install the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files

Java 6 - http://www.oracle.com/technetwork/java/javase/downloads/jce-6-download-429243.html
Java 7 - http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html
